"""scripts/render-caddy-config.sh — safe managed-config upgrade for the
installed Caddyfile (production incident: an already-running installation's
/etc/centralpay-bridge/Caddyfile was never regenerated by `centralpay
update`, nor by install.sh's "keep existing configuration" rerun path, so a
security-relevant template change like Referer ct/sig log redaction could
ship in source but never reach production).

Deterministic subprocess tests — no root, no real Docker daemon required for
this file. `docker` on PATH is replaced with a wrapper that records its
invocation and returns a scripted exit code, so these tests exercise the
SCRIPT's own control flow (extraction, rendering, diffing, backup, atomic
replace, exit-code contract) independent of Caddy's actual parser -- that
real-parser correctness is covered separately by the `@pytest.mark.docker`
tests below (gated on a real Docker daemon) and by the existing
`.github/workflows/ci.yml` "docker" job, which runs the real `caddy:2`
image directly.
"""

import os
import re
import shlex
import shutil
import subprocess
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = PROJECT_ROOT / "scripts" / "render-caddy-config.sh"
TEMPLATE = PROJECT_ROOT / "deploy" / "caddy" / "Caddyfile.template"

OLD_CADDYFILE = """{
\temail old@example.com
\tadmin off
}

old.example.com {
\tencode gzip
\tlog {
\t\toutput stdout
\t\tformat filter {
\t\t\twrap json
\t\t\tfields {
\t\t\t\trequest>uri query {
\t\t\t\t\treplace sig REDACTED
\t\t\t\t\treplace ct REDACTED
\t\t\t\t}
\t\t\t}
\t\t}
\t}
\theader {
\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"
\t}
\trequest_body {
\t\tmax_size 64KB
\t}
\t@public {
\t\tpath /api/custom-payment /api/centralpay/callback /health/live /health/ready /static/*
\t}
\thandle @public {
\t\treverse_proxy api:8000
\t}
\thandle {
\t\trespond "Not found" 404
\t}
}
"""


def _write_fake_docker(bindir: Path, *, validate_ok: bool = True) -> Path:
    """A `docker` stub on PATH: records every invocation and exits
    according to `validate_ok` -- fast and deterministic, independent of
    whether a real Docker daemon or the caddy:2 image is available."""
    call_log = bindir / "docker_calls.log"
    script = bindir / "docker"
    body = f'printf "%s\\n" "$*" >> {shlex.quote(str(call_log))}\n'
    body += "exit 0\n" if validate_ok else 'echo "fake caddy validate: syntax error" >&2\nexit 1\n'
    script.write_text("#!/usr/bin/env bash\n" + body)
    script.chmod(0o755)
    return call_log


@pytest.fixture
def sandbox(tmp_path):
    install = tmp_path / "install"
    config = tmp_path / "config"
    bindir = tmp_path / "bin"
    (install / "deploy" / "caddy").mkdir(parents=True)
    (install / "scripts").mkdir(parents=True)
    shutil.copy(TEMPLATE, install / "deploy" / "caddy" / "Caddyfile.template")
    config.mkdir()
    bindir.mkdir()
    return {"install": install, "config": config, "bindir": bindir}


def _run(
    sandbox,
    *,
    validate_ok: bool = True,
    env_extra: dict[str, str] | None = None,
    args: list[str] | None = None,
):
    call_log = _write_fake_docker(sandbox["bindir"], validate_ok=validate_ok)
    env = {
        "PATH": f"{sandbox['bindir']}:/usr/bin:/bin:/usr/sbin:/sbin",
        "CENTRALPAY_INSTALL_DIR": str(sandbox["install"]),
        "CENTRALPAY_CONFIG_DIR": str(sandbox["config"]),
        **(env_extra or {}),
    }
    result = subprocess.run(
        ["bash", str(SCRIPT), *(args or [])],
        capture_output=True,
        text=True,
        timeout=30,
        env=env,
    )
    return result, call_log


def _target(sandbox) -> Path:
    return sandbox["config"] / "Caddyfile"


def _confirm_active(sandbox) -> subprocess.CompletedProcess[str]:
    """Simulate the caller's post-restart step (`--confirm-active`) --
    writes the durable activation marker for whatever is currently on disk."""
    env = {
        "PATH": f"{sandbox['bindir']}:/usr/bin:/bin:/usr/sbin:/sbin",
        "CENTRALPAY_INSTALL_DIR": str(sandbox["install"]),
        "CENTRALPAY_CONFIG_DIR": str(sandbox["config"]),
    }
    return subprocess.run(
        ["bash", str(SCRIPT), "--confirm-active"],
        capture_output=True, text=True, timeout=30, env=env,
    )


# --- 1. fresh install --------------------------------------------------------


def test_fresh_install_renders_new_caddyfile(sandbox):
    result, call_log = _run(
        sandbox,
        env_extra={"PAYMENT_DOMAIN": "pay.example.com", "TLS_EMAIL": "ops@example.com"},
    )
    assert result.returncode == 2, result.stderr
    content = _target(sandbox).read_text()
    assert "pay.example.com {" in content
    assert "email ops@example.com" in content
    assert call_log.exists()  # validation was invoked


def test_fresh_install_without_domain_or_email_fails_closed(sandbox):
    result, _ = _run(sandbox)
    assert result.returncode == 1
    assert not _target(sandbox).exists()


# --- 2. upgrade from old config ----------------------------------------------


def test_upgrade_from_old_config_adds_referer_redaction(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    content = _target(sandbox).read_text()
    assert "headers>Referer" in content
    assert "old.example.com {" in content  # domain preserved
    assert "email old@example.com" in content  # TLS email preserved


# --- 3. already-current config is idempotent ---------------------------------


def test_idempotent_second_run_is_a_pure_noop(sandbox):
    """True idempotency requires the caller to have confirmed activation
    (simulating a successful restart) between the two runs -- see
    test_unconfirmed_activation_reports_changed_even_with_unchanged_content
    for what happens without that call."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    first, first_log = _run(sandbox)
    assert first.returncode == 2
    content_after_first = _target(sandbox).read_text()
    log_after_first = first_log.read_text() if first_log.exists() else ""
    assert log_after_first != ""  # the first run DID validate via docker

    confirm = _confirm_active(sandbox)
    assert confirm.returncode == 0, confirm.stderr

    second, second_log = _run(sandbox)
    assert second.returncode == 0, second.stderr
    assert _target(sandbox).read_text() == content_after_first
    # The diff short-circuit happens BEFORE validation -- the log must be
    # byte-identical to after the first run: no NEW docker call appended.
    log_after_second = second_log.read_text() if second_log.exists() else ""
    assert log_after_second == log_after_first


def test_unconfirmed_activation_reports_changed_even_with_unchanged_content(sandbox):
    """The activation-tracking fix: a process interrupted after this
    script's atomic replace but BEFORE the caller's restart+confirm-active
    (a crash, Ctrl-C, OOM kill, systemd timeout) must not silently report
    "0 unchanged" on the next run while Caddy is still serving the OLD
    config -- content matches, but activation was never confirmed, so the
    next run must still report 2 (needs restart), without re-touching the
    file (no new backup, content byte-identical)."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    first, first_log = _run(sandbox)
    assert first.returncode == 2
    content_after_first = _target(sandbox).read_text()
    backups_after_first = list(sandbox["config"].glob("Caddyfile.bak.*"))
    assert len(backups_after_first) == 1
    log_after_first = first_log.read_text() if first_log.exists() else ""
    assert log_after_first != ""  # the first run DID validate via docker

    # No --confirm-active call here -- simulating the interrupted case.
    second, second_log = _run(sandbox)
    assert second.returncode == 2, second.stderr
    assert _target(sandbox).read_text() == content_after_first  # untouched
    # No re-validation, no new backup: content was already correct, only
    # the activation signal was missing -- the log must be byte-identical
    # to after the first run (no NEW docker call appended).
    log_after_second = second_log.read_text() if second_log.exists() else ""
    assert log_after_second == log_after_first
    backups_after_second = list(sandbox["config"].glob("Caddyfile.bak.*"))
    assert len(backups_after_second) == 1

    # Confirming activation now makes the NEXT run a true no-op.
    confirm = _confirm_active(sandbox)
    assert confirm.returncode == 0, confirm.stderr
    third, _ = _run(sandbox)
    assert third.returncode == 0, third.stderr


def test_confirm_active_requires_an_existing_caddyfile(sandbox):
    result = _confirm_active(sandbox)
    assert result.returncode == 1
    assert not (sandbox["config"] / ".caddy-active-sha256").exists()


def test_confirm_active_writes_the_marker_matching_target_hash(sandbox):
    import hashlib

    _target(sandbox).write_text(OLD_CADDYFILE)
    result = _confirm_active(sandbox)
    assert result.returncode == 0, result.stderr
    marker = sandbox["config"] / ".caddy-active-sha256"
    assert marker.exists()
    assert marker.read_text().strip() == hashlib.sha256(OLD_CADDYFILE.encode()).hexdigest()
    assert oct(marker.stat().st_mode)[-3:] == "600"


# --- 3b. --check mode: a read-only status query for `centralpay status`/
#     `diagnose` (see caddy_activation_status_line in scripts/centralpay).
#     Must NEVER write TARGET, NEVER back up, NEVER touch ACTIVE_MARKER,
#     NEVER invoke docker/caddy validate -- only ever report drift.


def test_check_mode_reports_drift_without_mutating_or_validating(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, call_log = _run(sandbox, args=["--check"])
    assert result.returncode == 2, result.stderr
    assert _target(sandbox).read_text() == OLD_CADDYFILE  # byte-identical, untouched
    assert not list(sandbox["config"].glob("Caddyfile.bak.*"))  # no backup created
    assert not (sandbox["config"] / ".caddy-active-sha256").exists()
    assert not call_log.exists()  # docker was never invoked for a --check


def test_check_mode_reports_up_to_date_and_confirmed_without_side_effects(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    first, first_log = _run(sandbox)  # render + replace (real run, not --check)
    assert first.returncode == 2
    confirm = _confirm_active(sandbox)
    assert confirm.returncode == 0, confirm.stderr
    content_before = _target(sandbox).read_text()
    marker_before = (sandbox["config"] / ".caddy-active-sha256").read_text()
    log_before = first_log.read_text() if first_log.exists() else ""

    result, call_log = _run(sandbox, args=["--check"])
    assert result.returncode == 0, result.stderr
    assert _target(sandbox).read_text() == content_before
    assert (sandbox["config"] / ".caddy-active-sha256").read_text() == marker_before
    # A pure content/marker compare needs no docker call -- the log must be
    # byte-identical to before this --check run (no NEW invocation appended).
    log_after = call_log.read_text() if call_log.exists() else ""
    assert log_after == log_before


def test_check_mode_reports_unconfirmed_activation_without_mutating(sandbox):
    """Content already matches the current template (a prior real run
    replaced it) but --confirm-active was never called -- e.g. the exact
    interrupted-after-restart scenario --check exists to surface loudly.
    Must still report 2 (needs restart) without writing anything new."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    first, first_log = _run(sandbox)
    assert first.returncode == 2
    content_after_first = _target(sandbox).read_text()
    backups_after_first = list(sandbox["config"].glob("Caddyfile.bak.*"))
    log_before = first_log.read_text() if first_log.exists() else ""

    result, call_log = _run(sandbox, args=["--check"])
    assert result.returncode == 2, result.stderr
    assert _target(sandbox).read_text() == content_after_first
    assert list(sandbox["config"].glob("Caddyfile.bak.*")) == backups_after_first
    assert not (sandbox["config"] / ".caddy-active-sha256").exists()
    log_after = call_log.read_text() if call_log.exists() else ""
    assert log_after == log_before  # no NEW docker call from --check


def test_check_mode_fails_closed_without_domain_or_email(sandbox):
    result, call_log = _run(sandbox, args=["--check"])
    assert result.returncode == 1
    assert not _target(sandbox).exists()
    assert not call_log.exists()


def test_check_mode_never_creates_config_dir_on_an_uninstalled_host(tmp_path):
    """A host with no CentralPay installation at all yet (no CONFIG_DIR) --
    e.g. `centralpay status` run against a broken/partial install -- must
    never have --check itself create CONFIG_DIR as a side effect of merely
    checking. The default (mutating) mode legitimately does via `install -d`;
    --check must not, since it is documented as never touching disk."""
    install = tmp_path / "install"
    config = tmp_path / "config"  # deliberately never created
    bindir = tmp_path / "bin"
    (install / "deploy" / "caddy").mkdir(parents=True)
    (install / "scripts").mkdir(parents=True)
    shutil.copy(TEMPLATE, install / "deploy" / "caddy" / "Caddyfile.template")
    bindir.mkdir()
    call_log = _write_fake_docker(bindir)
    env = {
        "PATH": f"{bindir}:/usr/bin:/bin:/usr/sbin:/sbin",
        "CENTRALPAY_INSTALL_DIR": str(install),
        "CENTRALPAY_CONFIG_DIR": str(config),
        "PAYMENT_DOMAIN": "pay.example.com",
        "TLS_EMAIL": "ops@example.com",
    }
    result = subprocess.run(
        ["bash", str(SCRIPT), "--check"],
        capture_output=True, text=True, timeout=30, env=env,
    )
    assert result.returncode == 2, result.stderr  # a fresh install has never been confirmed active
    assert not config.exists()  # --check must never create CONFIG_DIR
    assert not call_log.exists()


# --- 4 & 5. domain / TLS-email (the two operator-supported values) preserved


def test_domain_value_preserved_exactly(sandbox):
    caddyfile = OLD_CADDYFILE.replace("old.example.com", "custom-domain.example.org")
    _target(sandbox).write_text(caddyfile)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    content = _target(sandbox).read_text()
    assert "custom-domain.example.org {" in content
    assert "old.example.com" not in content


def test_tls_email_preserved_exactly(sandbox):
    caddyfile = OLD_CADDYFILE.replace("old@example.com", "operator-custom@example.org")
    _target(sandbox).write_text(caddyfile)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    content = _target(sandbox).read_text()
    assert "email operator-custom@example.org" in content
    assert "old@example.com" not in content


# --- 6. malformed existing config --------------------------------------------


def test_malformed_existing_config_fails_closed(sandbox):
    _target(sandbox).write_text("this is not a caddyfile at all\njust some text\n")
    result, call_log = _run(sandbox)
    assert result.returncode == 1
    assert _target(sandbox).read_text() == "this is not a caddyfile at all\njust some text\n"
    assert not call_log.exists()  # never even reached validation


def test_existing_config_missing_email_line_fails_closed(sandbox):
    broken = "{\n\tadmin off\n}\n\nold.example.com {\n\trespond 200\n}\n"
    _target(sandbox).write_text(broken)
    result, _ = _run(sandbox)
    assert result.returncode == 1
    assert _target(sandbox).read_text() == broken


# --- 7. generated invalid config (template itself corrupted) ----------------


def test_generated_invalid_config_never_written(sandbox):
    """Even if the CANDIDATE render itself were somehow invalid (simulated
    here by a fake docker validate that fails), the target must never be
    replaced with it."""
    result, _ = _run(
        sandbox,
        validate_ok=False,
        env_extra={"PAYMENT_DOMAIN": "pay.example.com", "TLS_EMAIL": "ops@example.com"},
    )
    assert result.returncode == 1
    assert not _target(sandbox).exists()


# --- 8 & 10. validation failure leaves the existing config untouched --------


def test_validation_failure_leaves_existing_config_byte_identical(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, _ = _run(sandbox, validate_ok=False)
    assert result.returncode == 1
    assert _target(sandbox).read_text() == OLD_CADDYFILE
    # No backup file either -- validation failed before any mutation began.
    backups = list(sandbox["config"].glob("Caddyfile.bak.*"))
    assert backups == []


# --- 9. backup created before mutation ---------------------------------------


def test_backup_created_before_replacing_existing_config(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    backups = list(sandbox["config"].glob("Caddyfile.bak.*"))
    assert len(backups) == 1
    assert backups[0].read_text() == OLD_CADDYFILE
    assert oct(backups[0].stat().st_mode)[-3:] == "600"


# --- 11. atomic replacement: no leftover temp files, correct permissions ----


def test_no_leftover_temp_candidate_files(sandbox):
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    leftovers = list(sandbox["config"].glob(".Caddyfile.candidate.*"))
    assert leftovers == []
    assert oct(_target(sandbox).stat().st_mode)[-3:] == "600"


def test_temp_candidate_cleaned_up_on_validation_failure(sandbox):
    result, _ = _run(
        sandbox,
        validate_ok=False,
        env_extra={"PAYMENT_DOMAIN": "pay.example.com", "TLS_EMAIL": "ops@example.com"},
    )
    assert result.returncode == 1
    leftovers = list(sandbox["config"].glob(".Caddyfile.candidate.*"))
    assert leftovers == []


# --- 14. secrets never printed -----------------------------------------------


def test_output_never_contains_unrelated_secret_markers(sandbox):
    """The script never reads or touches centralpay.env / DB passwords /
    API keys -- planting decoy secret values in the environment and
    confirming they never appear in stdout/stderr guards against an
    accidental future `env` dump or similar mistake."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    decoy_secret = "DECOY_SECRET_VALUE_zzq93nvk"
    result, _ = _run(sandbox, env_extra={"CENTRALPAY_TEST_DECOY_SECRET": decoy_secret})
    assert decoy_secret not in result.stdout
    assert decoy_secret not in result.stderr
    # Domain/email (not secrets) legitimately do appear.
    assert "old.example.com" in result.stdout


# --- 15. mandatory directives cannot silently drift away ---------------------


_MANDATORY_SNIPPETS = (
    "admin off",
    "replace sig REDACTED",
    "replace ct REDACTED",
    "headers>Referer regexp",
    "Strict-Transport-Security",
    "X-Content-Type-Options",
    "X-Frame-Options",
    'Referrer-Policy "no-referrer"',
    "Permissions-Policy",
    "-Server",
    "max_size 64KB",
    "path /api/custom-payment /api/centralpay/callback /health/live /health/ready /static/*",
    'respond "Not found" 404',
)


def test_every_mandatory_directive_present_after_upgrade(sandbox):
    """Not just the one known historical gap (Referer redaction) -- EVERY
    mandatory directive in the current template must end up in an upgraded
    Caddyfile, by construction (full re-render), so this test protects
    against any FUTURE mandatory-directive drift too, not only the one
    that already happened once."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    result, _ = _run(sandbox)
    assert result.returncode == 2, result.stderr
    content = _target(sandbox).read_text()
    for snippet in _MANDATORY_SNIPPETS:
        assert snippet in content, f"missing mandatory directive: {snippet!r}"
    # Cross-check against the template itself: every mandatory line in the
    # CURRENT template (i.e. every line untouched by the two placeholders)
    # must appear verbatim in the rendered output.
    template_text = TEMPLATE.read_text()
    for line in template_text.splitlines():
        stripped = line.strip()
        if not stripped or "{{" in stripped:
            continue
        assert stripped in content, f"template line dropped from rendered output: {stripped!r}"


# --- activation: restart gated on exit code (perform_update / install.sh) ---


def test_perform_update_restarts_caddy_only_when_config_changed(tmp_path):
    """scripts/centralpay's perform_update must call `compose restart caddy`
    ONLY when render-caddy-config.sh reports a real change (exit 2), never
    on an unchanged config (exit 0) -- proven at the source-text level
    (the exact conditional gating), complementing the fake-docker
    behavioral tests above."""
    source = (PROJECT_ROOT / "scripts" / "centralpay").read_text()
    body = source[source.index("perform_update() {") :]
    body = body[: body.index("\nperform_rollback() {")]
    assert 'render-caddy-config.sh" || caddy_sync_rc=$?' in body
    assert "caddy_sync_rc" in body
    # The restart call is conditioned on caddy_sync_rc == 2, and appears
    # strictly after that assignment.
    rc_check_i = body.index('"$caddy_sync_rc" -eq 2')
    restart_i = body.index("compose restart caddy")
    assert rc_check_i < restart_i
    assert 'if [[ "$caddy_sync_rc" -ne 0 && "$caddy_sync_rc" -ne 2 ]]; then' in body


def test_perform_update_aborts_before_build_on_caddy_sync_failure():
    """A fatal Caddy-config sync (exit 1) must abort BEFORE compose
    build/migrate/restart -- never a half-applied update."""
    source = (PROJECT_ROOT / "scripts" / "centralpay").read_text()
    body = source[source.index("perform_update() {") :]
    body = body[: body.index("\nperform_rollback() {")]
    sync_call_i = body.index("render-caddy-config.sh")
    build_i = body.index("compose build")
    assert sync_call_i < build_i


def test_install_sh_syncs_caddy_for_both_fresh_and_rerun_paths():
    """install.sh must call sync_caddy_config unconditionally (outside the
    KEEP_EXISTING branch) -- this is the actual fix for the "keep existing
    configuration" rerun gap, distinct from perform_update's fix for
    `centralpay update`."""
    source = (PROJECT_ROOT / "install.sh").read_text()
    main_body = source[source.index("main() {") :]
    # sync_caddy_config must be called exactly once, and NOT inside the
    # `if [[ "$KEEP_EXISTING" != "true" ]]; then ... fi` block that guards
    # write_configuration.
    keep_existing_block_start = main_body.index('if [[ "$KEEP_EXISTING" != "true" ]]; then')
    keep_existing_block_end = main_body.index("\n    fi\n", keep_existing_block_start)
    guarded_block = main_body[keep_existing_block_start:keep_existing_block_end]
    assert "sync_caddy_config" not in guarded_block
    assert "sync_caddy_config" in main_body[keep_existing_block_end:]


def test_perform_update_activates_caddy_before_build_not_gated_on_deploy_success(tmp_path):
    """Review finding (P1, round 3): activation was previously nested inside
    `if compose up -d --wait; then`, so a LATER build/health-check failure
    left an already-validated, already-written Caddy config never activated
    -- and `centralpay rollback` never touches Caddy either (deliberately,
    see SECURITY.md), so the advertised recovery path could never have
    closed that gap. The restart + --confirm-active calls must now appear
    BEFORE `compose build`, textually outside the `if compose up -d --wait;
    then ... else ... fi` block, so activation happens regardless of
    whether the app-level deploy later succeeds."""
    source = (PROJECT_ROOT / "scripts" / "centralpay").read_text()
    body = source[source.index("perform_update() {") :]
    body = body[: body.index("\nperform_rollback() {")]

    restart_i = body.index("compose restart caddy")
    confirm_i = body.index('render-caddy-config.sh" --confirm-active')
    build_i = body.index("compose build")
    up_wait_i = body.index('if compose up -d --wait; then')

    # Both activation calls happen before the build step...
    assert restart_i < build_i
    assert confirm_i < build_i
    # ...and both happen before the `if compose up -d --wait; then` line
    # itself, i.e. strictly outside (before) that conditional block, not
    # nested inside its success branch.
    assert restart_i < up_wait_i
    assert confirm_i < up_wait_i


def test_install_sh_activates_existing_caddy_container_before_deploy_stack():
    """Mirrors the perform_update fix: on a rerun where caddy is ALREADY
    running (an existing install), activation must not be gated on
    deploy_stack succeeding -- install.sh has no rollback command either,
    so a deploy_stack failure after an ungated activation would strand the
    config written-but-inactive until the operator happens to retry."""
    source = (PROJECT_ROOT / "install.sh").read_text()
    main_body = source[source.index("main() {") :]
    restart_i = main_body.index("docker compose --project-directory \"$INSTALL_DIR\" restart caddy")
    deploy_i = main_body.index("\n    deploy_stack\n")
    assert restart_i < deploy_i


def test_install_sh_confirms_fresh_caddy_container_after_deploy_stack():
    """A genuinely fresh install has no caddy container to restart before
    deploy_stack creates it -- the durable confirm-active call for that
    case must come AFTER deploy_stack (once the container is confirmed
    up), not before, and must be reachable only when there was no existing
    container to restart pre-deploy."""
    source = (PROJECT_ROOT / "install.sh").read_text()
    main_body = source[source.index("main() {") :]
    deploy_i = main_body.index("\n    deploy_stack\n")
    post_deploy = main_body[deploy_i:]
    assert "CADDY_EXISTING_CONTAINER" in post_deploy
    assert '--confirm-active' in post_deploy
    ensure_fee_i = post_deploy.index("ensure_initial_fee_policy")
    confirm_i = post_deploy.index("--confirm-active")
    assert confirm_i < ensure_fee_i


# --- shell hygiene ------------------------------------------------------------


@pytest.mark.skipif(not shutil.which("shellcheck"), reason="shellcheck is not installed")
def test_script_passes_shellcheck():
    # shellcheck is an OS package, not a Python dependency of `.[dev]` --
    # the documented `pip install -e ".[dev]"` + `pytest -q` setup does not
    # guarantee it, and the dedicated CI "ShellCheck" job already covers
    # this; skip cleanly here rather than erroring the whole unit suite on
    # an environment that simply doesn't have the binary.
    result = subprocess.run(
        ["shellcheck", str(SCRIPT)], capture_output=True, text=True, timeout=30
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_script_syntax_is_valid_bash():
    result = subprocess.run(
        ["bash", "-n", str(SCRIPT)], capture_output=True, text=True, timeout=10
    )
    assert result.returncode == 0, result.stderr


# --- real Docker / real caddy:2 (gated) --------------------------------------


def _docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    try:
        subprocess.run(
            ["docker", "info"], capture_output=True, timeout=10, check=True
        )
    except Exception:
        return False
    return True


pytestmark_docker = pytest.mark.skipif(
    not _docker_available(), reason="a working Docker daemon is required"
)


@pytest.mark.docker
@pytestmark_docker
def test_real_caddy_validates_a_fresh_render(sandbox):
    # This test intentionally does NOT fake docker -- uses the real system
    # PATH so the script actually shells out to `docker run caddy:2 caddy
    # validate`, proving the rendered output is genuinely valid Caddyfile
    # syntax under the exact image the stack runs.
    env = {
        **os.environ,
        "CENTRALPAY_INSTALL_DIR": str(sandbox["install"]),
        "CENTRALPAY_CONFIG_DIR": str(sandbox["config"]),
        "PAYMENT_DOMAIN": "pay.example.com",
        "TLS_EMAIL": "ops@example.com",
    }
    real_result = subprocess.run(
        ["bash", str(SCRIPT)], capture_output=True, text=True, timeout=60, env=env
    )
    assert real_result.returncode == 2, real_result.stderr
    assert re.search(r"pay\.example\.com \{", _target(sandbox).read_text())


@pytest.mark.docker
@pytestmark_docker
def test_real_caddy_validates_the_upgraded_old_config(sandbox):
    """The exact production scenario end-to-end against the real image: an
    old-shaped Caddyfile (URI redaction only) is upgraded, and the RESULT
    is genuinely valid Caddyfile syntax under caddy:2 -- not just a string
    match, an actual `caddy validate` pass."""
    _target(sandbox).write_text(OLD_CADDYFILE)
    env = {
        **os.environ,
        "CENTRALPAY_INSTALL_DIR": str(sandbox["install"]),
        "CENTRALPAY_CONFIG_DIR": str(sandbox["config"]),
    }
    real_result = subprocess.run(
        ["bash", str(SCRIPT)], capture_output=True, text=True, timeout=60, env=env
    )
    assert real_result.returncode == 2, real_result.stderr
    upgraded = _target(sandbox).read_text()
    assert "headers>Referer" in upgraded
    assert "old.example.com {" in upgraded

    validate = subprocess.run(
        [
            "docker", "run", "--rm", "--network", "none",
            "-v", f"{_target(sandbox)}:/tmp/Caddyfile:ro",
            "caddy:2", "caddy", "validate",
            "--config", "/tmp/Caddyfile", "--adapter", "caddyfile",
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert validate.returncode == 0, validate.stdout + validate.stderr
