#!/usr/bin/env bash
# CentralPay Bridge — safe managed-config upgrade for the installed Caddyfile.
#
# Run by install.sh (fresh install AND a "keep existing configuration"
# rerun) and by scripts/centralpay's `update`. Never run this by hand
# unless you understand the ownership model below.
#
# Production incident this fixes: an installed /etc/centralpay-bridge/
# Caddyfile is NOT regenerated by a plain `centralpay update` (docker
# compose only rereads a bind-mounted file's bytes on container start, and
# `git checkout` + `compose build`/`up -d` never touched the file at all),
# and install.sh's own "keep existing configuration" rerun path skipped
# Caddyfile rendering entirely. Together, a security-relevant change to
# deploy/caddy/Caddyfile.template (e.g. the Referer ct/sig log-redaction
# rule) could ship in source but never reach an already-running production
# host — the exact gap a manual production fix had to work around.
#
# Ownership model: deploy/caddy/Caddyfile.template has exactly two
# operator-supplied values -- the payment domain and the TLS/ACME email --
# everything else (logging/redaction, security headers, request-size cap,
# route allowlist, `admin off`) is APPLICATION-MANAGED and must always
# match the currently checked-out template exactly. There is no supported
# way to hand-edit the installed Caddyfile beyond those two values; doing
# so is not a documented configuration surface and previous full-file
# `render_template` overwrites (every fresh install, and every install.sh
# rerun that did NOT choose "keep existing configuration") already
# discarded any such edit.
#
# Strategy: extract the two operator values from the EXISTING installed
# Caddyfile (or accept them explicitly via PAYMENT_DOMAIN/TLS_EMAIL, for a
# fresh install with no existing file yet), fully re-render the CURRENT
# template with them, and only touch anything on disk if the rendered
# result actually differs byte-for-byte from what's installed -- this is
# what makes the operation idempotent and keeps drift impossible by
# construction rather than by a line-level merge that could itself go
# stale. The candidate is validated with the exact `caddy:2` image the
# stack runs (`caddy validate`) BEFORE anything on disk changes; the
# previous file is backed up before the atomic replace; a failed
# validation leaves the existing, working configuration completely
# untouched. Activation (restarting the caddy container so it rereads the
# bind-mounted file) is the CALLER's responsibility, gated on this
# script's exit code -- Caddy's admin API is intentionally disabled
# (`admin off` in the template, and no admin port is published in
# docker-compose.yml), so a hot `caddy reload` is architecturally
# unavailable by design; a container restart is the only supported
# activation path (this matches the real production recovery: `caddy
# reload` failed with "connection refused" against the disabled admin
# API, and restarting the container picked up the bind-mounted file).
#
# Exit codes (the caller MUST branch on this, never assume success):
#   0  already up to date AND confirmed active -- nothing was changed,
#      caller should not restart.
#   2  the installed file does not match what Caddy has been CONFIRMED
#      restarted with -- either because the content just changed (backed
#      up and replaced here), or because a PRIOR run's replace was never
#      followed by a successful `--confirm-active` call (see below). The
#      caller MUST restart the caddy container, then call this script
#      again with `--confirm-active`.
#   1  a real error (missing template, unreadable/malformed existing
#      config, invalid domain/email, failed validation, failed backup, or
#      failed atomic replace) -- the existing configuration, if any, was
#      left completely untouched. The caller must treat this as fatal.
#
# --check mode (a THIRD, read-only invocation form, alongside the default
# render-and-replace form and --confirm-active): reports the exact same
# 0/1/2 exit-code contract as above, but NEVER writes anything -- no
# candidate write beyond a throwaway temp file it always removes itself, no
# backup, no replace of TARGET, no docker/caddy validation, no marker
# write. Intended for a lightweight, always-safe status query (`centralpay
# status`/`diagnose`) to answer "is the installed Caddyfile currently in
# sync with the checked-out source, and was that content actually
# confirmed activated" without performing (or risking) any of the mutating
# work the default form does. This does NOT close the bootstrap gap
# documented in SECURITY.md/AGENTS.md -- a process already running the OLD
# perform_update never reaches any NEW code, --check mode included -- it
# only makes the resulting drift loudly visible on the very next command
# invocation instead of silently persisting until an operator happens to
# rerun `update` or the installer.
#
# Activation tracking: a container restart activating a freshly-replaced
# file is the CALLER's responsibility (see below), but simply diffing file
# CONTENT is not enough to know activation actually happened -- an update
# or install.sh run interrupted after this script's atomic replace but
# before the caller's restart (a crash, an operator Ctrl-C, an OOM kill, a
# systemd timeout) would leave the on-disk file already matching the new
# template while the RUNNING Caddy process still serves the old one. The
# next run would then see identical file content and report "0 unchanged"
# forever, even though the security-relevant config was never actually
# activated. To close that gap, a small durable marker
# (CONFIG_DIR/.caddy-active-sha256, the sha256 of the Caddyfile content
# Caddy was LAST CONFIRMED restarted with) is compared alongside the file
# content: exit 0 requires BOTH to match. The caller writes this marker by
# invoking `render-caddy-config.sh --confirm-active` immediately after a
# successful restart -- never assumed automatically. A host upgrading to
# THIS version of the script for the first time has no marker yet, so its
# very next run reports "changed" (2) once even if the file content is
# already correct -- a single harmless extra restart, not a bug.
#
# Never prints the full rendered Caddyfile or backup contents; the domain
# and TLS email are not secrets (the domain is publicly visible in the TLS
# certificate itself) and may appear in log lines.

set -Eeuo pipefail
umask 077

INSTALL_DIR="${CENTRALPAY_INSTALL_DIR:-/opt/centralpay-bridge}"
CONFIG_DIR="${CENTRALPAY_CONFIG_DIR:-/etc/centralpay-bridge}"
TEMPLATE="${INSTALL_DIR}/deploy/caddy/Caddyfile.template"
TARGET="${CONFIG_DIR}/Caddyfile"
ACTIVE_MARKER="${CONFIG_DIR}/.caddy-active-sha256"
# Pinned to the exact tag docker-compose.yml's caddy service runs, so
# validation can never pass against a different Caddy version than what
# actually serves traffic.
CADDY_IMAGE="${CENTRALPAY_CADDY_IMAGE:-caddy:2}"

log()  { printf '[centralpay-caddy] %s\n' "$*"; }
fail() { printf '[centralpay-caddy] ERROR: %s\n' "$*" >&2; exit 1; }

sha256_of() {
    # $1 = path. Prints the hex digest only (no filename), portable across
    # the GNU (sha256sum) and BSD/macOS (shasum) coreutils layouts.
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

CHECK_ONLY=false
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=true

if [[ "${1:-}" == "--confirm-active" ]]; then
    # Called by the caller (install.sh / scripts/centralpay) immediately
    # after a successful `compose restart caddy` -- and ONLY then; a
    # restart that itself failed must never reach this call (both callers'
    # restart is a bare command under `set -e`, so a failure already
    # aborts before this point).
    [[ -f "$TARGET" ]] || fail "No Caddyfile at ${TARGET} to confirm activation for."
    install -d -m 0700 "$CONFIG_DIR"
    sha256_of "$TARGET" > "$ACTIVE_MARKER" || fail "Could not write the activation marker ${ACTIVE_MARKER}."
    chmod 600 "$ACTIVE_MARKER"
    log "Activation confirmed for the current Caddy configuration."
    exit 0
fi

validate_domain() {
    [[ "$1" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,62}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,62}[a-zA-Z0-9])?)+$ ]]
}

validate_email() {
    [[ "$1" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

[[ -f "$TEMPLATE" ]] || fail "Template not found: ${TEMPLATE} (is ${INSTALL_DIR} a real checkout?)."

# --- Resolve the two operator-supplied values -------------------------------
#
# Explicit PAYMENT_DOMAIN/TLS_EMAIL (a fresh install, before any Caddyfile
# exists) win; otherwise both are extracted from the currently installed
# Caddyfile. A malformed/missing existing file with no explicit override is
# a hard failure -- there is no safe default to invent for a production
# TLS/routing configuration.

domain="${PAYMENT_DOMAIN:-}"
tls_email="${TLS_EMAIL:-}"

if [[ -z "$domain" || -z "$tls_email" ]]; then
    if [[ ! -f "$TARGET" ]]; then
        fail "No existing Caddyfile at ${TARGET} and PAYMENT_DOMAIN/TLS_EMAIL were not provided."
    fi
    if [[ -z "$tls_email" ]]; then
        tls_email=$(grep -E '^[[:space:]]*email[[:space:]]+' "$TARGET" | head -1 | awk '{print $2}' || true)
    fi
    if [[ -z "$domain" ]]; then
        # The site-address line: a bare hostname token followed by `{` at
        # end of line. Distinct from the global options block's opening
        # line, which is a bare `{` with nothing before it.
        domain=$(grep -E '^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?[[:space:]]*\{[[:space:]]*$' "$TARGET" \
            | head -1 | awk '{print $1}' || true)
    fi
fi

[[ -n "$domain" ]] || fail "Could not determine the payment domain (existing Caddyfile may be malformed: ${TARGET})."
[[ -n "$tls_email" ]] || fail "Could not determine the TLS email (existing Caddyfile may be malformed: ${TARGET})."
validate_domain "$domain" || fail "Resolved payment domain fails validation; refusing to render a Caddyfile from it."
validate_email "$tls_email" || fail "Resolved TLS email fails validation; refusing to render a Caddyfile from it."

# --- Render deterministically (literal substitution -- no sed/regex risk
#     from a domain/email value containing a metacharacter) -----------------

render_candidate() {
    local content
    content=$(cat "$TEMPLATE"; printf x)
    content=${content%x}
    content=${content//"{{PAYMENT_DOMAIN}}"/"$domain"}
    content=${content//"{{TLS_EMAIL}}"/"$tls_email"}
    printf '%s' "$content"
}

if [[ "$CHECK_ONLY" == "true" ]]; then
    # A plain system-temp scratch file, never inside CONFIG_DIR: --check
    # must never create CONFIG_DIR (as `install -d` below would) merely by
    # having been run against a host with no installation yet. Atomicity
    # with TARGET is irrelevant here -- this candidate is only ever
    # compared, never moved into place.
    candidate=$(mktemp) || fail "Cannot create a temporary scratch file."
else
    install -d -m 0700 "$CONFIG_DIR"
    candidate=$(mktemp "${CONFIG_DIR}/.Caddyfile.candidate.XXXXXX") \
        || fail "Cannot create a temporary file in ${CONFIG_DIR}."
fi
trap 'rm -f "$candidate"' EXIT
render_candidate > "$candidate"
chmod 600 "$candidate"

content_unchanged=false
if [[ -f "$TARGET" ]] && cmp -s "$candidate" "$TARGET"; then
    content_unchanged=true
fi

if [[ "$content_unchanged" == "true" ]]; then
    active_hash=""
    [[ -f "$ACTIVE_MARKER" ]] && active_hash=$(cat "$ACTIVE_MARKER" 2>/dev/null || true)
    if [[ -n "$active_hash" ]] && [[ "$active_hash" == "$(sha256_of "$TARGET")" ]]; then
        log "Caddy configuration already up to date and confirmed active (domain: ${domain})."
        exit 0
    fi
    # Content already matches -- nothing to validate/backup/replace -- but
    # activation was never confirmed (a prior run's restart was skipped,
    # failed, or was interrupted before `--confirm-active` ran; or this is
    # the first run of this script version on this host, see the header).
    # Signal "needs restart" without touching the file.
    log "Caddy configuration content is current but activation was not confirmed; caller must restart and confirm."
    trap - EXIT
    rm -f "$candidate"
    exit 2
fi

if [[ "$CHECK_ONLY" == "true" ]]; then
    # Read-only status query: report the drift, touch nothing else. Never
    # validates (no docker dependency for a status check), never backs up,
    # never replaces TARGET, never writes ACTIVE_MARKER.
    log "Caddy configuration differs from the currently checked-out source, or a prior change was never confirmed active (domain: ${domain}). --check performed no changes."
    trap - EXIT
    rm -f "$candidate"
    exit 2
fi

# --- Validate the CANDIDATE with the real image before touching anything
#     on disk. Never assumes `caddy`/`docker` output is safe to print in
#     full; the exit status alone gates activation, but the diagnostic text
#     itself is operational (paths/line numbers), never a secret, so it is
#     relayed to stderr for the operator. -----------------------------------

command -v docker >/dev/null 2>&1 || fail "docker is required to validate the Caddy configuration."

if ! validation_output=$(docker run --rm --network none \
        -v "${candidate}:/tmp/Caddyfile:ro" \
        "$CADDY_IMAGE" caddy validate --config /tmp/Caddyfile --adapter caddyfile 2>&1); then
    printf '%s\n' "$validation_output" >&2
    fail "Candidate Caddy configuration failed validation. The existing configuration was left unchanged."
fi

# --- Backup, then atomic same-filesystem replace ----------------------------

if [[ -f "$TARGET" ]]; then
    backup_path="${TARGET}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
    cp -p "$TARGET" "$backup_path" || fail "Could not back up the existing Caddyfile before replacing it."
    chmod 600 "$backup_path"
    log "Backed up existing configuration to ${backup_path}."
fi

mv -f -- "$candidate" "$TARGET" || fail "Could not atomically replace ${TARGET}."
trap - EXIT

log "Caddy configuration updated (domain: ${domain}). Restart the caddy container to activate it."
exit 2
